services:
  devcontainer:
    image: ubuntu:22.04
    init: true
    volumes:
      - ..:/workspaces/rust-devcontainer-template:cached

# If you are experiencing performance issues during the build when targeting a
# volume-mounted directory, you can also persist the target to a Docker volume
# as shown in the following example.

# services:
#   devcontainer:
#     image: ubuntu:22.04
#     init: true
#     volumes:
#       - ..:/workspaces/rust-devcontainer-template:cached
#       - cargo-target:/workspaces/rust-devcontainer-template/target
#
# volumes:
#   cargo-target:
