services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    init: true
    volumes:
      - ..:/workspaces/rust-devcontainer-boilerplate:cached
# If you are experiencing performance issues during the build when targeting a
# volume-mounted directory, you can also persist the target to a Docker volume
# as shown in the following example.

# services:
#   devcontainer:
#     image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
#     init: true
#     volumes:
#       - ..:/workspaces/rust-devcontainer-boilerplate:cached
#       - cargo-target:/workspaces/rust-devcontainer-boilerplate/target
#
# volumes:
#   cargo-target:
